# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Puntuación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario del paciente sobre la opinión', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='OpinionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_propuesto', models.TextField(help_text='Diagnóstico propuesto por el médico')),
                ('recomendaciones', models.TextField(help_text='Recomendaciones del médico')),
                ('tratamiento_sugerido', models.TextField(blank=True, help_text='Tratamiento sugerido por el médico', null=True)),
                ('comentarios_adicionales', models.TextField(blank=True, help_text='Comentarios adicionales del médico', null=True)),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Indica si el caso requiere seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opinión Médica',
                'verbose_name_plural': 'Opiniones Médicas',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(help_text='Observaciones del seguimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve de la solicitud', max_length=200)),
                ('descripcion_caso', models.TextField(help_text='Descripción detallada del caso médico')),
                ('diagnostico_inicial', models.TextField(blank=True, help_text='Diagnóstico inicial del médico tratante', null=True)),
                ('tratamiento_actual', models.TextField(blank=True, help_text='Tratamiento actual que está recibiendo el paciente', null=True)),
                ('especialidad_requerida', models.CharField(help_text='Especialidad médica requerida para la segunda opinión', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_revision', 'En Revisión'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Prioridad de la solicitud', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Opinión',
                'verbose_name_plural': 'Solicitudes de Opinión',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
