# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opiniones_medicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente que califica la opinión', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinionmedica',
            name='medico',
            field=models.ForeignKey(help_text='Médico que emite la opinión', on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='opinion',
            field=models.OneToOneField(help_text='Opinión médica calificada', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='opiniones_medicas.opinionmedica'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='medico',
            field=models.ForeignKey(help_text='Médico que realiza el seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='opinion',
            field=models.ForeignKey(help_text='Opinión médica a la que pertenece el seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='opiniones_medicas.opinionmedica'),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, help_text='Médico asignado para la segunda opinión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente que solicita la segunda opinión', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinionmedica',
            name='solicitud',
            field=models.OneToOneField(help_text='Solicitud asociada a esta opinión', on_delete=django.db.models.deletion.CASCADE, related_name='opinion_medica', to='opiniones_medicas.solicitudopinion'),
        ),
    ]
