# Generated by Django 5.2.4 on 2025-07-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '__first__'),
        ('opiniones_medicas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudopinion',
            name='equipo_asignado',
            field=models.ForeignKey(blank=True, help_text='Equipo de trabajo asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to='equipos.equipotrabajo'),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='estadio',
            field=models.CharField(blank=True, help_text='Estadio del cáncer (ej: I, II, III, IV)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='fecha_diagnostico',
            field=models.DateField(blank=True, help_text='Fecha del diagnóstico inicial', null=True),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='tipo_cancer',
            field=models.CharField(blank=True, help_text='Tipo de cáncer (ej: mama, pulmón, colon, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudopinion',
            name='tratamientos_previos',
            field=models.TextField(blank=True, help_text='Tratamientos previos recibidos', null=True),
        ),
    ]
