# Generated by Django 5.2.4 on 2025-07-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones_medicas', '0003_solicitudopinion_equipo_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudopinion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_revision', 'En Revisión'), ('revision_pendiente', 'Revisión Pendiente'), ('aprobada', 'Aprobada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20),
        ),
    ]
