# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.core.validators
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo temporal', upload_to='temp/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo Temporal',
                'verbose_name_plural': 'Archivos Temporales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del documento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del documento', null=True)),
                ('archivo', models.FileField(help_text='Archivo del documento', upload_to=documentos.models.upload_to_documents, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'])])),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('subido', 'Subido'), ('modificado', 'Modificado'), ('eliminado', 'Eliminado'), ('descargado', 'Descargado')], help_text='Acción realizada', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la acción', null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de documento', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de documento', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de documento está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
    ]
