# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('opiniones_medicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivotemporal',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que subió el archivo temporal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='solicitud',
            field=models.ForeignKey(help_text='Solicitud a la que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='opiniones_medicas.solicitudopinion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='documento',
            field=models.ForeignKey(help_text='Documento al que pertenece el historial', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento'),
        ),
    ]
