# Generated by Django 5.2.4 on 2025-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email al que se envió el código', max_length=254)),
                ('codigo', models.CharField(help_text='Código de verificación de 6 dígitos', max_length=6)),
                ('tipo', models.CharField(choices=[('registro', 'Registro de Usuario'), ('recuperacion', 'Recuperación de Contraseña'), ('cambio_email', 'Cambio de Email')], default='registro', help_text='Tipo de verificación', max_length=20)),
                ('datos_temporales', models.JSONField(blank=True, help_text='Datos temporales del usuario para el registro', null=True)),
                ('usado', models.BooleanField(default=False, help_text='Indica si el código ya fue usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha de expiración del código')),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del paciente en kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Sexo del paciente', max_length=1, null=True),
        ),
    ]
