# Generated by Django 5.2.4 on 2025-07-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadOncologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la especialidad oncológica', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la especialidad', null=True)),
                ('icono', models.CharField(default='fas fa-stethoscope', help_text='Icono FontAwesome para la especialidad', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la especialidad está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidad Oncológica',
                'verbose_name_plural': 'Especialidades Oncológicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo de trabajo', max_length=200, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción del equipo y sus funciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el equipo está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('coordinador', models.ForeignKey(blank=True, help_text='Médico coordinador del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_coordinados', to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(help_text='Especialidad oncológica del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='equipos.especialidadoncologica')),
            ],
            options={
                'verbose_name': 'Equipo de Trabajo',
                'verbose_name_plural': 'Equipos de Trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('especialidad', 'Por Especialidad'), ('tipo_cancer', 'Por Tipo de Cáncer'), ('estadio', 'Por Estadio'), ('edad_paciente', 'Por Edad del Paciente'), ('prioridad', 'Por Prioridad')], help_text='Criterio de asignación', max_length=20)),
                ('valor', models.CharField(help_text='Valor del criterio (ej: pulmón, mama, etc.)', max_length=200)),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad de la regla (1 = más alta)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la regla está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_asignacion', to='equipos.equipotrabajo')),
            ],
            options={
                'verbose_name': 'Regla de Asignación',
                'verbose_name_plural': 'Reglas de Asignación',
                'ordering': ['prioridad', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_equipo', models.CharField(choices=[('coordinador', 'Coordinador'), ('oncologo', 'Oncólogo'), ('radiologo', 'Radiólogo'), ('patologo', 'Patólogo'), ('cirujano', 'Cirujano'), ('radioterapeuta', 'Radioterapeuta'), ('enfermero', 'Enfermero Oncológico'), ('psicologo', 'Psicólogo'), ('nutricionista', 'Nutricionista'), ('farmaceutico', 'Farmacéutico'), ('otro', 'Otro')], default='oncologo', help_text='Rol del miembro en el equipo', max_length=20)),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='equipos.equipotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
                'verbose_name_plural': 'Miembros de Equipo',
                'unique_together': {('equipo', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='equipotrabajo',
            name='miembros',
            field=models.ManyToManyField(help_text='Miembros del equipo', related_name='equipos_miembro', through='equipos.MiembroEquipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
